#!/usr/bin/env bash

usage() {
	local rst green
	rst=$(tput sgr0 2>/dev/null)
	green=$(tput setaf 2 2>/dev/null)

	cat <<-EOF
${green}run$rst - Run Gleam Project ($BICS_VERSION)
Usage: run [command]

Subcommands:
	-w, --watch		run in watch mode$rst
	-o, --once		run once$rst
	-t, --test		test in watch mode$rst
	-h, --help		show this message$rst
	EOF
}

once() {
	pushd ./app
	gleam run
	popd
}

watch() {
	pushd ./app
	wgo -xdir=./build clear :: gleam run
	popd
}

test_watch() {
	pushd ./app
	wgo -xdir=./build clear :: gleam test
	popd
}

case "$1" in
	-w | --watch) watch		;;
	-o | --once ) once		;;
	-t | --test ) test_watch	;;
	-h | --help ) usage >&2; exit 0	;;
	*) usage >&2; exit 1		;;
esac
